site_name: Artisan Kit
pages:
- Home: 'index.md'
- ArtisanKit Module: 'ArtisanKit.md'
- Classes: [
{ArtisanKit.Control: 'ArtisanKit.Control.md'},
{ArtisanKit.ScrollEvent: 'ArtisanKit.ScrollEvent.md'}
]
- Version History: 'History.md'
theme: mkdocs
include_next_prev: false